### ISSUE TITLE
each time in mulsitite we save the values of the fields, we destroy the admin changes in the subsites

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#204]
Now, we can have in the multisite a value for a field, like in illustrator. Because is not freeze, the new books or the current books will see such property with that value, and the administrators can change the value and use it. But if the super admin save again the page of the multiste (without even a change in the illustrator field) the admin value of illustrator would be by mistake overwrite by the value of the superadmin. that is an issue,

because is not freeze but if the superadmin save the page again, the value change in all of the subsites.... that is like freeze in the end.

Or freeze by default, or we need to be able to allow to overwrite the fields by the admins of the subsites.
![captura de pantalla 2017-10-24 a las 12 33 21](https://user-images.githubusercontent.com/3929177/31938583-3d3239b6-b8b8-11e7-9355-ea087f304a30.png)

**Comment by MashRoofa** [comment]
Now the admin can block super admin from changing their metadata properties (not frozen ones). Though the admin cannot block the super admin from creating new frozen properties and changing them. This method ensures that the super admin has full access but the same time it ensures that no mistakes are happening due to unexpected overwrites.
