### ISSUE TITLE
To export/import the metadata

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#24]
If we make a migration of the conten, we need to be able to export and import the metadata of the book. 

The id of the metadata will be the name of the post. Not the ID of the post, because afther the migration, the ID will be different for each topic, but the name will be always the same.

**Comment by colomet** [comment]
take a review, maybe is a good start point
https://github.com/pippinsplugins/Settings-Import-and-Export-Example-Plugin

**Comment by masaka222** [comment]
Right now pressbooks works in that way. Everything is being exported fine. The problem comes when you need to import the chapter. Only the fields in the **$meta_to_update** variable can be imported.

![screen shot 2017-05-15 at 16 44 29](https://cloud.githubusercontent.com/assets/23406636/26191713/4c778240-3baf-11e7-901a-e634b08ca04d.png)

**Comment by MashRoofa** [comment]
After modifying pressbooks with this hook "pb_import_metakeys" the chapter metadata is now able to be  transferred through exporting and importing. No need for future modifications as the chapters fields (meta_keys) are passed automatically to the hook by the database.
