### ISSUE TITLE
schema for root theme

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#6]
To use the classes http://schema.org/WebSite with all the types.

**Comment by masaka222** [comment]
Normally we would put the WebSite code in the footer_function as the rest of the code, with an if statement if ( is_home() ). 
The problem is that in the html of the root page, the </body> and </html> tags are being produced twice so our microdata code is being produced twice too. (wp_footer action is being triggered after the </body> tag)
We need to add the code for the WebSite to a new function that will be called in the header().
