### ISSUE TITLE
extend PB Book metadata

### ISSUE THREAD

**Issue by colomet** [Books4Languages/pressbooks-metadata#7]
Now, PB don´t use all the types of the classe Books, we need to extend http://schema.org/Book

**Comment by masaka222** [comment]
bookEdition and illustrator will be a text field. Then we need to use bookFormat. This one for now can be a check box, and ask if the book will be exported or not. If it is checked, bookFormatType will be EBook. Otherwise it will not be used. Finally for the isbn we need to ask the community if we can access this information.
